
services:
  mysql:
    image: mysql:9.0.1
    container_name: skim_through_db
    environment:
      MYSQL_ROOT_PASSWORD: skim1through!
      MYSQL_DATABASE: skim_through
      
    ports:
      - "3310:3306"
    
    volumes:
      - ./data/:/var/lib/mysql

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
  
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock